(* func EBNF Grammar *)
white_space   = { " " | "\t" | "\n" | "\r" } ;
space         = { " " | "\t" | "\n" | "\r" }+ ;
nonzero_digit = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ; 
digit         = "0" | nonzero_digit ; 
letter        = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | 
                "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | 
                "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | 
                "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" ; 
char          = letter | digit | symbol ; (* where symbol is any printable unicode symbol *)

id = ( letter | "_" ) , { letter | digit | "_" } ;

program = [ import ] , expr ;

(* imports *)
import_lib = string
		   | string , white_space , "*"
		   | string , white_space , id ;
import = "import" , white_space , "(" , white_space , { import_lib } , white_space , ")";

(* type literals *)
int_digit = digit | ( nonzero_digit , { digit } ) ;
int = { int_digit | "_" };
hex_digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
			"8" | "9" | "A" | "B" | "C" | "D" | "E" | "F" ; 
hex_int = "0x" , { hex_digit | "_" };
binary_digit = "0" | "1";
binary_int = "0b" , { binary_digit | "_"};

float  = int , "." , int ;

number = [ "-" ] , ( int | hex_int | binary_int | float ) ;

string = ( '"' , { char } , '"' ) 
       | ( "'" , { char } , "'" ) ;

literal = number | string;

collection_access = expr , "[" , expr , "]" ;

(* List of expressions surrounded by {} *)
expr_block = "{" , { expr } , "}";

(* generics - [F] , [T, K] *)
generic_params = "[" , white_space , id , { white_space , "," , white_space , id } , white_space "]";

(* Type name *)
type_name = id , [ generic_params ]; (* Option[T] , Foo , int , Result[T, E], etc *)

(* assignment expression *)
type_annotation = ":" , type_name ; (* This might not be needed *)
assign_expr = "let" space , id , white_space , [ type_annotation ] , white_space , "=" , white_space , expr ;

(* with expression *)
(* with foo = open('file.txt') {...} *)
with_expr = "with", space , id , "=", white_sapce , expr , white_space , expr_block  ;

(* scope expression *)
scope_param = id , white_space , [ "," ];
scope_param_list = { param } ,;
scope_expr = "scope", space ,  scope_param_list , expr_block

(* if else expression*)
(* if x == 5 {...} else {...} *)
if_expr = "if", space , expr , white_space , expr_block , "else" , white_space , expr_block ;

(* case expression *)
case_pattern = id , white_space , "(" , id_list , ")"; (* TODO define this *)
case_list = { case_pattern , "=>" , expr };
case_expr = "case", space , expr , white_space , "{" , case_list , "}" ;

(* functions *)
param = id , white_space , id , [ "," ];
param_list = { param } ,;
func_sig = "fun", space , type_name , "(", param_list ")" , white_space , type_name ;
func_def = func_sig , white_space , expr_block;
func_call = expr , white_space , "(" , expr_list , ")" ;

(* Type Definitions *)

(* interfaces *)
field_sig = id , white_space , type_name , [ "=" , expr ] ;
interface_body = { field_sig | func_sig } ;
interface = "interface" , white_space , type_name , "{" white_space , interface_body , white_space ,"}";

(* structs *)
struct_body = { field_sig };
struct = "struct" , white_space , type_name , "{" , white_space , struct_body , white_space ,"}";

(* unions *)
union_body = { field_sig };
union = "union" , white_space , type_name , "{" , white_space , union_body , white_space ,"}";

(* impl *)
impl_body = { func_def } ;
impl = "impl" , [ white_space , type_name ] , white_space , "for" , white_space , type_name , "{" , impl_body , "}";

(* enums *)
enum_body = { id , [ "(" , param_list , ")" ] };
enum = "enum" , white_space , type_name , "{" , white_space , enum_body , white_space ,"}";

(* type alias*)
type_alias = "type" , white_space , id , white_space , "=" , white_space , type_name;

type_definition = interface | struct | union | impl | enum | type_alias;

(* Loops *)
id_list = { id , white_space }; 
for_loop = "for" , white_space , id_list , white_space , "in" , white_space , expr , white_space , expr_block;
while_loop = "while" , white_space , expr , white_space , expr_block;
loop_expr = for_loop | while_loop ;

(* operators *)
binary_operator = "==" 
	| "!=" 
	| "<" 
	| ">" 
	| "<="
	| ">="
	| "and"
	| "or"
	| "xor"
	| "+" 
	| "-"
	| "*"
	| "/"
	| "." ;

unary_operator = "not" ;

(* grand unifying expression *)
expr = expr , operator , expr
	| unary_operator , expr
	| if_expr
	| case_expr
	| with_expr
	| assign_expr
	| func_def 
	| func_call
	| type_definition
	| loop
	| collection_access